#!/bin/bash
declare -a ARRAY
let I=0
echo "enter the no. of elements"
read COUNT
while [ $I -lt $COUNT ]; do
	echo "enter element"
	read ARRAY[$I]
	let I=I+1
done
echo "the contents of the array is :"
echo ${ARRAY[@]}

let I=0
echo "enter the element to be searched : "
read ELE
while [ $I -lt $COUNT ]; do
	if [ "${ARRAY[$I]}" == "$ELE" ]
	then
		echo "element found at position: $I"
		let flag=1
	else
		let flag=0
	fi
	let I=I+1
done
if [ "$flag" -eq "0" ]
then 
	echo "element not found"
fi
